version: '3.7'

services: 

    node:
        build: 
            context: ./
            dockerfile: ./Dockerfile
        image: node_cluster:latest
        deploy:
            replicas: 2
        ports:
            - 3000:3000
        environment: 
            - NODE_ENV="production"